version: '3'

services:
  app:
    # image: donmichael/geolocator
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
  ciram-api:
    image: sofkost/aresiboriskanalysis
    ports:
      - "8080:8080"
    depends_on: 
      - app
