# Generated by Django 2.2.9 on 2020-03-03 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borders', '0002_auto_20200122_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='border',
            name='mpoly',
        ),
        migrations.RemoveField(
            model_name='border',
            name='poly',
        ),
    ]
